services:
  - type: web
    name: osint-telegram-bot
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt && pip install "maigret==0.4.4" --no-deps && pip install "aiohttp>=3.9.0,<3.10" --upgrade
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: HIBP_API_KEY
        sync: false
      - key: VERIPHONE_API_KEY
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: PORT
        value: 8080
